version: '3.9'

services:
  olivetti-face-app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: g25ai1023/olivetti-face-app:0.1
    container_name: olivetti-face-app
    ports:
      - "5001:5000"
    restart: unless-stopped